sudo: required
services: 
  - docker
before_install: 
  - docker build -t arseniibylym/categories_list -f ./client/Dockerfile.dev ./client
script: 
  - docker run arseniibylym/categories_list npm run coverage