version: '3'
services: 
  mongo: 
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  server: 
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports: 
      - "5000:5000"
    environment: 
      - RUN_WITH_DOCKER=true
    volumes:
      - /app/node_modules
      - /app/client
      - .:/app